# Generated by Django 3.2.7 on 2021-10-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scorecard_name', models.CharField(max_length=255)),
                ('step', models.IntegerField()),
                ('milestone', models.CharField(max_length=255)),
                ('score', models.CharField(choices=[(0, 'Not yet achieved'), (1, 'Patially achieved'), (2, 'Fully achieved')], max_length=1)),
                ('narrative', models.CharField(max_length=600)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
