# Generated by Django 3.2.7 on 2021-10-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='narrative',
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='score',
            field=models.CharField(choices=[[0, 'Not yet achieved'], [1, 'Patially achieved'], [2, 'Fully achieved']], max_length=50),
        ),
    ]
