# Generated by Django 3.2.7 on 2021-10-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20211010_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='score',
            field=models.IntegerField(),
        ),
    ]
