# Generated by Django 3.2.7 on 2021-10-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_indicator_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='score',
            field=models.IntegerField(choices=[(0, 'Not yet achieved'), (1, 'Patially achieved'), (2, 'Fully achieved')]),
        ),
    ]
