# Generated by Django 3.2.8 on 2021-10-19 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_indicator_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='indicator',
            name='scorecard_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.scorecard'),
        ),
    ]
